### ISSUE TITLE
Ability to change the base url

### ISSUE THREAD

**Issue by evokelektrique** [cesargb/laravel-magiclink#107]
Feature request for changing the APP_URL while it's being generated with Laravel's built in `url()` helper at here [MagicLink.php#L76C7-L76C7](https://github.com/cesargb/laravel-magiclink/blob/master/src/MagicLink.php#L76C7-L76C7)

I'll probably make a PR for it

**Comment by evokelektrique** [comment]
I've made a PR for it:
https://github.com/cesargb/laravel-magiclink/pull/108

**Comment by pvledoux** [comment]
Hi! This one would be super useful since we are hosting behind a proxy, the origin so domain is not the same than the exposed one. I managed to resolve the issue by extending the original model, but if it feels a bit clunky

**Comment by cesargb** [comment]
Hi! 

I release a new version with this feature: [v2.22.0](https://github.com/cesargb/laravel-magiclink/releases/tag/v2.20.0)

Thanks: @evokelektrique , @pvledoux
