### ISSUE TITLE
Erro no arquivo MagicLink

### ISSUE THREAD

**Issue by LeoMachado94** [cesargb/laravel-magiclink#2]
Tem um erro no arquivo MagicLink, na linha 35 para ser mais específico. Tem que retirar o espaço/tab da função config pois ao mudar o path da url no arquivo de config ele não reconhece devido a esse espaço.

**Comment by cesargb** [comment]
Thanks for the report, I should have prepared more tests to detects this issues. Please feel free to upload a pull with the change if you want.

**Comment by cesargb** [comment]
@LeoMachado94 Hello, I close this issue in v1.1.1 (https://github.com/cesargb/laravel-magiclink/commit/c774b8d0004171c80f04830985c1242168bf9496).

Thanks for your report.
