### ISSUE TITLE
Error after publishing magiclink config file

### ISSUE THREAD

**Issue by laquanmax** [cesargb/laravel-magiclink#20]
After publishing the config file magiclink laravel throws an exception **Illuminate \ Contracts \ Container \ BindingResolutionException** **_Target class [view] does not exist._**.

I were able to resolve it by changing the response error to a string instead of a response function or view in config/magiclink.php:51

I used a fresh installation of laravel 7.6.2 using PHP version 7.4.5 on Ubuntu 18.04 LTS

**Comment by cesargb** [comment]
Hello @laquanmax, thanks for your issue. I think that in this moment the best solution is remove this option.

**Comment by cesargb** [comment]
Fix this issue in v2.2.2
