### ISSUE TITLE
Action Serialization with Postgres

### ISSUE THREAD

**Issue by dannydinges** [cesargb/laravel-magiclink#21]
Running into an issue with the serialized string being store in Postgres. The text datatype seems to not like the escaping in the serialized string. The following seems to be the same issue.

https://github.com/Crinsane/LaravelShoppingcart/issues/362

**Comment by dannydinges** [comment]
I think the solution to this is to json_encode/json_decode for inserting and pulling from the DB. Also have you considered using Illuminate\Queue\SerializesModels on the Action classes?

**Comment by cesargb** [comment]
@dannydinges I need time to test this issue. Other option is encode in base64 after to save in database.

**Comment by dannydinges** [comment]
@cesargb Sorry for being pushy but have you had a chance to put some thought into this? I'd love to use this package but in it's current state it's not usable with this issue.

**Comment by cesargb** [comment]
@dannydinges This issue is fixed in the new version 2.3. I have done tests under postgresql 12.2 and all of them have passed.

Thanks.
