### ISSUE TITLE
Add redirect path in config, if link is not valid

### ISSUE THREAD

**Issue by yelyas20** [cesargb/laravel-magiclink#22]
I need to set a link that contains message to user that says your link is not valid because...
The link should be set in config file
Thanks

**Comment by cesargb** [comment]
I've been thinking about this for a few days. Maybe something like this:

```php
'invalid_response' => [
    /*
     | Method called when magiclink is invalid, method accepted: response, view, redirect, abort
   */
    'method' => 'response',
    'arguments => [
        'forbidden', 
        '403'
    ],
],
```

**Comment by dannydinges** [comment]
I submitted a pull request to define the controller where you could do whatever you'd want. I think it'd cover this situation for the user as well.

**Comment by yelyas20** [comment]
> I submitted a pull request to define the controller where you could do whatever you'd want. I think it'd cover this situation for the user as well.

Thank you

**Comment by cesargb** [comment]
@yelyas20 In the version 2.4.0, you have this features: https://github.com/cesargb/laravel-magiclink#custom-response-when-magiclink-is-invalid

I hope the documentation is clear enough.

**Comment by yelyas20** [comment]
Thank you good man
با احترام، الیاس یاوری
َlinkedin.com/in/y-elyas <https://www.linkedin.com/in/y-elyas/>

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/16/20,
06:32:52 PM

**Comment by yelyas20** [comment]
Thank you good man
