### ISSUE TITLE
SQL error when changing token length

### ISSUE THREAD

**Issue by vanushwashere** [cesargb/laravel-magiclink#31]
Database migration creates a column for the token with a maximum length of 100 symbols. But you can change that token length value in configuration to a value bigger than 100 and get the `Data too long for column 'token' at row 1 ` SQL error.

**Comment by cesargb** [comment]
Thanks, as a first measure it would increase the size in the migrate file, in this case with varchar(255) or varchar(191).

But even so I do not see an optimal way to solve the problem definitely without size limit.

**Comment by vanushwashere** [comment]
You can fallback to the maximum possible value if the length set more then it and log a warning

**Comment by cesargb** [comment]
@vanushwashere feel free to send in a PR to fix this.

**Comment by vanushwashere** [comment]
@cesargb here it is #36

**Comment by cesargb** [comment]
@vanushwashere thanks for your PR
