### ISSUE TITLE
How to use Custom Disk

### ISSUE THREAD

**Issue by Aliakbari1994** [cesargb/laravel-magiclink#32]
I want to get the file from ftp disk and give it to DownloadFileAction(). What can I do to do this?

**Comment by cesargb** [comment]
You can get file from other disk with action `ResponseAction`, sample:

```php
$action = new ResponseAction(function () {
    return Storage::disk('ftp')->download('text.txt');
});

$url = MagicLink::create($action)->url;
```
Although it would be better to incorporate this possibility in the action `DownloadFileAction`. It would be a good idea to add this functionality.
