### ISSUE TITLE
File Name

### ISSUE THREAD

**Issue by Aliakbari1994** [cesargb/laravel-magiclink#34]
I want to change the file name when downloading the file. What can I do about this?

**Comment by cesargb** [comment]
@Aliakbari1994 Hello you can change the file name with DownloadAction, for this use the second argument, sample:

```php
$action = new DownloadFileAction('text.txt', 'other_file_name.txt');

$magiclink = MagicLink::create($action);
```

Then you donwload the file called other_file_name.txt
