### ISSUE TITLE
Feature request: Ask for access code before download start

### ISSUE THREAD

**Issue by rabol** [cesargb/laravel-magiclink#38]
Hi

Would be cool to be able to create a download link that require the visitor to enter access code before the download start

**Comment by cesargb** [comment]
Hi @rabol,

It would be a great idea for this component. If you want to collaborate with the project, feel free to send a pull request.

Thanks

**Comment by rabol** [comment]
I got it working by:
Adding a new field to the MagicLink - access_code
Then I disabled the standard route in the config
copied the original route definition 
The I added a middleware

Now... I only have one problem and that is that after download it does not redirect to th path in the config file

if you like this approach I can try to put a PR together

**Comment by cesargb** [comment]
By thinking about it, I was also planting an approach like yours. Generate a middleware to request the code and then allow the action. In your approach, perhaps, you would add a new path to request the previous code. The action is only allowed if no code has been specified or you have the correct code session. In any case, send the PR and we will see together if it would be enough or we propose a change.

**Comment by rabol** [comment]
PR created, let me know if it looks okay for you
