### ISSUE TITLE
Set path in cookie

### ISSUE THREAD

**Issue by danielbehrendt** [cesargb/laravel-magiclink#41]
I think it would be better to set the "path" in cookie to the current path of the request instead of setting it only to "/"

```
cookie(
    'magic-link-access-code',
    encrypt($request->get('access-code')),
    0,
    $request->getPathInfo()
)
```
otherwise all MagicLinks with the same access code will be visible if this was entered already on another link.

**Comment by cesargb** [comment]
In that case, the cookie stored in the browser would expose the URL that allows the action. A possible solution would be to encrypt this data together with the access code in the cookie value.

**Comment by danielbehrendt** [comment]
Yes, you're right. But your suggestion sound like a good solution.

**Comment by danielbehrendt** [comment]
@cesargb Do you hav any plans to integrate this and do a new release?

**Comment by cesargb** [comment]
@danielbehrendt if you want, you can send a PR
