### ISSUE TITLE
phpstorm detecting an error

### ISSUE THREAD

**Issue by CovertError** [cesargb/laravel-magiclink#66]
so I'm using multiple authentication guards and when i try to get the id of a user like this

`            'patient_id' => Auth::guard('users')->user()->id,
`
I get an error in phpstorm that says this
<img width="597" alt="Screen Shot 2022-06-17 at 3 41 39 PM" src="https://user-images.githubusercontent.com/34497804/174300274-1e959e9a-979f-4bcd-a391-339010ff59b1.png">
 
but functionally everything works

**Comment by cesargb** [comment]
the `MagicLink\Test\TestSupport\ CustomAutenticable` class should not be used outside of test environments.

**Comment by CovertError** [comment]
I'm not using it but for some reason phpstorm is detecting it when I use Auth::guard('users')->user()->id

**Comment by fabianwennink** [comment]
I experience the same issue. PhpStorm somehow detects the test class and applies it to the Auth facade.

![image](https://user-images.githubusercontent.com/5164060/180171316-da278025-8199-402a-871e-bb94d5a84e40.png)
