### ISSUE TITLE
Possible to set "remember me"?

### ISSUE THREAD

**Issue by Laupet** [cesargb/laravel-magiclink#93]
Great package you have made! Thanks.

Is it possible in any way to set "remember me" for the login action?
I want the login session to last longer than the global SESSION_LIFETIME that is defined in .env.

**Comment by cesargb** [comment]
Thanks! In this moment, you only can make a `CustomAction`, example:

```php
use MagicLink\Actions\ActionAbstract;

class LoginWithRememberAction extends ActionAbstract
{
    public function __construct(public int $userId)
    {
    }

    public function run()
    {
        Auth::loginUsingId($this->id, true);

        return parent::run();
    }
}
```

But this feature will be interesting add in the `LoginAction`, please, give me a few days to pull this request or, if you wish, you can send a PR.
