### ISSUE TITLE
How do I customize my code access view?

### ISSUE THREAD

**Issue by miguelbonifaz** [cesargb/laravel-magiclink#95]
I'm sorry for the confusion, but I couldn't get to this page to customize it.

**Comment by cesargb** [comment]
Currently it is not possible to modify the template that requests the access code.

Although this functionality could be incorporated. If you want, you can submit a PR that provides this feature.

**Comment by cesargb** [comment]
You can customize it with version PR #98 in v2.17.0.

You can see: https://github.com/cesargb/laravel-magiclink#protect-with-an-access-code
